# Generated by Django 6.0.3 on 2026-04-06 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryCustomization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voltage', models.PositiveIntegerField(help_text='Voltage (V)')),
                ('capacity', models.PositiveIntegerField(help_text='Capacity (Ah)')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('electrical', 'Electrical Fault (عطل كهربائي)'), ('mechanical', 'Mechanical Fault (عطل ميكانيكي)'), ('general', 'General Maintenance (صيانة عامة)')], max_length=50)),
                ('description', models.TextField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.TextField()),
                ('name_tr', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image_url', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_tr', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='ebike', max_length=100)),
                ('stock', models.IntegerField(default=1)),
                ('power', models.CharField(blank=True, help_text='e.g. 1000W', max_length=50, null=True)),
                ('range', models.CharField(blank=True, help_text='e.g. 50km', max_length=50, null=True)),
                ('weight', models.CharField(blank=True, help_text='e.g. 25kg', max_length=50, null=True)),
                ('speed', models.CharField(blank=True, help_text='e.g. 45km/h', max_length=50, null=True)),
                ('is_spark_certified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akakce_url', models.TextField(blank=True, null=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('ebike', 'E-bike (دراجة كهربائية)'), ('scooter', 'E-Scooter (سكوتر كهربائي)')], max_length=50)),
                ('brand_model', models.CharField(max_length=255)),
                ('condition', models.TextField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
