# Generated by Django 5.0.4 on 2026-04-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Swarder', max_length=255)),
                ('tagline', models.TextField(default='Akıllı Hareketlilik Çözümleri')),
                ('whatsapp_number', models.CharField(default='905387845388', max_length=50)),
                ('contact_email', models.EmailField(default='info@swarder.com', max_length=254)),
                ('contact_address', models.TextField(default='Istanbul, Turkey')),
                ('maintenance_contact', models.CharField(default='905387845388', max_length=50)),
            ],
        ),
    ]
