# Generated by Django 5.0.4 on 2026-04-07 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage_phone_contactmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_ar', models.TextField(blank=True, null=True)),
                ('subtitle_tr', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField()),
                ('link_url', models.CharField(default='/store', max_length=255)),
                ('button_text_ar', models.CharField(default='تسوق الآن', max_length=100)),
                ('button_text_tr', models.CharField(default='Şimdi Al', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
